export const ROLES = {
  READ_OBJECTS: 'READ_OBJECTS',
  READ_ACCOUNTS: 'READ_ACCOUNTS',
  READ_LOGINS: 'READ_LOGINS',
  READ_GUILDS: 'READ_GUILDS',
  READ_CITIES: 'READ_CITIES',
  READ_RESOURCES: 'READ_RESOURCES',
} as const;
